language: python
python: "2.7"
before_install:
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
install: "./scanblog/bin/install.sh"
script: 
 - "python scanblog/manage.py test"     # plain tests
 - "python scanblog/manage.py test btb" # live tests with selenium
